### PR TITLE
Refactor test using mruby

### PR DESCRIPTION
**Pull request by matsumoto-r**

### CODE REVIEW

**Comment by matsumoto-r** [comment]
Travis CI failed because of https://github.com/luisbebop/mruby-polarssl/pull/5 .

**Comment by matsumoto-r** [comment]
Oops, mod_process_security must run with root since apache parent process need linux capability.

**Comment by matsumoto-r** [comment]
Hi, @k0u5uk3 

Please review it!

**Comment by k0u5uk3** [comment]
I reviewed this PR. 
I learned how to write test of mruby-mtest. Thank you.

**Pull request merged**
